
dataset:
  num_targets: 1
  readout: mean
  max_atoms: 20
  otf_graph: false
  eval_model_name: mp20
  train_max_epochs: 1000
  early_stopping_patience: 100000
  teacher_forcing_max_epoch: 500

  common_args: &common_args
    prop:
      - mean_distance
    niggli: true
    primitive: False
    graph_method: crystalnn
    lattice_scale_method: scale_length
    preprocess_workers: 30
    tolerance: 0.1
    use_space_group: false
    use_pos_index: false

  train:
    name: train
    path: data/2d_structure/2d_structure_csv_ehull_200_condition/train.csv
    save_path: data/2d_structure/2d_structure_csv_ehull_200_condition/train_ori.pkl
    <<: *common_args
  val:
    name: val
    path: data/2d_structure/2d_structure_csv_ehull_200_condition/val.csv
    save_path: data/2d_structure/2d_structure_csv_ehull_200_condition/val_ori.pkl
    <<: *common_args

  test:
    name: test
    path: data/2d_structure/2d_structure_csv_ehull_200_condition/test.csv
    save_path: data/2d_structure/2d_structure_csv_ehull_200_condition/test_ori.pkl
    <<: *common_args

  sample:
    formula: MoS2
    num_evals: 10
  generation:
    total_num: 10
    property_value: [0.2]

model:
  __name__: CSPDiffusionWithGuidanceD3PM
  decoder_cfg:
    hidden_dim: 512
    latent_dim: 256
    max_atoms: 100
    num_layers: 6
    act_fn: silu
    dis_emb: sin
    num_freqs: 128
    edge_style: fc
    max_neighbors: 20
    cutoff: 7
    ln: true
    ip: true
    pred_type: true
    smooth: false
  beta_scheduler_cfg:
    timesteps: 1000
    scheduler_mode: cosine
  sigma_scheduler_cfg:
    timesteps: 1000
    sigma_begin: 0.005
    sigma_end: 0.5
  discrete_scheduler_cfg:
    timesteps: 1000
    num_classes: 100
    forward_type: uniform

  time_dim: 256
  cost_lattice: 1
  cost_coord: 1
  cost_type: 20
  property_input_dim: 1
  property_dim: 512
  # pretrained: ./checkpoints/diffcsp_2d_w_guidance/latest.pdparams


lr_cfg:
  learning_rate: 0.001
  factor: 0.6
  patience: 30
  min_lr: 0.0001
epochs: 1000
batch_size: 256
num_workers: 0
save_path: "./checkpoints/diffcsp_2d_w_guidance_d3pm"

sample_step_lr: 0.00001
