Global:
  epochs: 500
  output_dir: ./output/digress_CHnmr
  save_freq: 100 # set 0 to disable saving during training
  log_freq: 500 # log frequency [step]
  start_eval_epoch: 1
  eval_freq: 1 # set 0 to disable evaluation during training
  seed: 42
  is_save_traj: False
  clip_grad: null
  ema_decay: 0      # 'Amount of EMA decay, 0 means off. A reasonable value  is 0.999.'
  pretrained_model_path: null # set your pretrained model path here

Metric:
  __name__: CSPMetric
  gt_file_path: "./data/mp_20/test.csv"

Model:
  __name__: Digress
  decoder_cfg:
    hidden_dim: 512
    latent_dim: 256
    max_atoms: 100
    num_layers: 6
    act_fn: silu
    dis_emb: sin
    num_freqs: 128
    edge_style: fc
    max_neighbors: 20
    cutoff: 7
    ln: true
    ip: true
  beta_scheduler_cfg:
    timesteps: 1000
    scheduler_mode: cosine
  sigma_scheduler_cfg:
    timesteps: 1000
    sigma_begin: 0.005
    sigma_end: 0.5
  time_dim: 256


Optimizer:
  __name__: AdamW
  beta1: 0.9
  beta2: 0.999
  lr:
    __name__: ReduceOnPlateau
    learning_rate: 0.002
    factor: 0.6
    by_epoch: True
    patience: 30
    min_lr: 0.0001
    indicator: "train_loss"


Dataset:
  train:
    dataset:
      __name__: CHnmrDataset
      path: "./data/CHnmr/train.csv"
      cache: True
      remove_h: True
    loader:
      num_workers: 0
      use_shared_memory: False
    sampler:
      __name__: DistributedBatchSampler
      shuffle: True
      drop_last: False
      batch_size: 32
  val:
    dataset:
      __name__: CHnmrDataset
      path: "./data/CHnmr/val.csv"
      cache: True
      remove_h: True
    sampler:
      __name__: BatchSampler
      shuffle: False
      drop_last: False
      batch_size: 32
  test:
    dataset:
      __name__: CHnmrDataset
      path: "./data/CHnmr/test.csv"
      cache: True
      remove_h: True
    sampler:
      __name__: BatchSampler
      shuffle: False
      drop_last: False
      batch_size: 32
  predict:
    dataset:
      __name__: GenDataset
      total_num: 20
      formula: MoSi2
    sampler:
      __name__: BatchSampler
      shuffle: False
      drop_last: False
      batch_size: 128
