# =========================================================
# Base dataset parameters (shared by train/val/test)
# =========================================================
dataset_base_params: &dataset_base_params
  build_structure_cfg:
    format: cif_str
    num_cpus: 10

# =========================================================
# Sampler configuration (reusable aliases)
# =========================================================
train_sampler: &train_sampler
  __class_name__: BatchSampler
  __init_params__:
    shuffle: True
    drop_last: False
    batch_size: 256 # 16 for 4 GPUs, total batch size = 16 * 4 = 64

val_sampler: &val_sampler
  __class_name__: BatchSampler
  __init_params__:
    shuffle: False
    drop_last: False
    batch_size: 128

test_sampler: &test_sampler
  __class_name__: DistributedBatchSampler
  __init_params__:
    shuffle: False
    drop_last: False
    batch_size: 128

# =========================================================
# Train / Validation / Test dataset configuration
# =========================================================
train:
  dataset:
    __class_name__: MP20Dataset
    __init_params__:
      <<: *dataset_base_params
      path: "${Run.data_dir}/mp_20/train.csv"
  loader:
    num_workers: 0
    use_shared_memory: False
  sampler: *train_sampler

val:
  dataset:
    __class_name__: MP20Dataset
    __init_params__:
      <<: *dataset_base_params
      path: "${Run.data_dir}/mp_20/val.csv"
  sampler: *val_sampler

test:
  dataset:
    __class_name__: MP20Dataset
    __init_params__:
      <<: *dataset_base_params
      path: "${Run.data_dir}/mp_20/test.csv"
  sampler: *test_sampler
