Global:
  label_names: ["PCE_ave"]
  do_train: True
  do_eval: False
  do_test: False

Trainer:
  max_epochs: 20
  seed: 1
  output_dir: ./output/transpolymer_opv
  save_freq: 1
  log_freq: 20
  start_eval_epoch: 1
  eval_freq: 1
  resume_from_checkpoint: null
  use_amp: False
  amp_level: "O1"
  eval_with_no_grad: True
  gradient_accumulation_steps: 1
  best_metric_indicator: "eval_metric"
  name_for_best_metric: "PCE_ave"
  greater_is_better: True
  compute_metric_during_train: True
  metric_strategy_during_eval: "epoch"
  use_visualdl: False
  use_wandb: False
  use_tensorboard: False
  tolerance: 5

Model:
  __class_name__: TransPolymerRegressor
  __init_params__:
    pretrained_model_path: ./ckpt/pretrain.pt
    pretrained_model_url: https://28bf65435bc4c13f5b89a153488f09972c18f7f4@git.aistudio.baidu.com/TransPolymer/TransPolymer123.git
    property_name: ${Global.label_names}
    tokenizer_name_or_path: roberta-base
    vocab_sup_file: ./data/vocab/vocab_sup_OPV.csv
    blocksize: 411
    smiles_key: CSMILES
    use_token_cache: True
    drop_rate: 0.1
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1
    data_mean: 0.0
    data_std: 1.0
    loss_type: mse_loss

Metric:
  PCE_ave:
    __class_name__: R2Metric
    __init_params__: {}

Optimizer:
  __class_name__: AdamW
  __init_params__:
    lr:
      __class_name__: Linear
      __init_params__:
        learning_rate: 0.00005
        warmup_epoch: 1
        warmup_start_lr: 0.0
        by_epoch: False
    weight_decay: 0.01
    no_weight_decay_name: "bias LayerNorm.bias LayerNorm.weight layer_norm.bias layer_norm.weight"

Dataset:
  transform:
    __class_name__: mean_std_scaling
    __init_params__: {}
  train:
    dataset:
      __class_name__: TransPolymerCsvDataset
      __init_params__:
        path: ./data/OPV.csv
        property_names: ${Global.label_names}
        smiles_key: CSMILES
    loader:
      num_workers: 0
      use_shared_memory: False
      collate_fn: DefaultCollator
    sampler:
      __class_name__: BatchSampler
      __init_params__:
        shuffle: True
        drop_last: False
        batch_size: 8
  val:
    dataset:
      __class_name__: TransPolymerCsvDataset
      __init_params__:
        path: ./data/OPV.csv
        property_names: ${Global.label_names}
        smiles_key: CSMILES
    loader:
      num_workers: 0
      use_shared_memory: False
      collate_fn: DefaultCollator
    sampler:
      __class_name__: BatchSampler
      __init_params__:
        shuffle: False
        drop_last: False
        batch_size: 8
  test:
    dataset:
      __class_name__: TransPolymerCsvDataset
      __init_params__:
        path: ./data/OPV.csv
        property_names: ${Global.label_names}
        smiles_key: CSMILES
    loader:
      num_workers: 0
      use_shared_memory: False
      collate_fn: DefaultCollator
    sampler:
      __class_name__: BatchSampler
      __init_params__:
        shuffle: False
        drop_last: False
        batch_size: 8

Predict:
  eval_with_no_grad: True
