Global:
  task: polymer_property_prediction
  model_name: TransPolymer
  property_name: "Conductivity [S/cm]"

Tokenizer:
  pretrained_name_or_path: roberta-base
  blocksize: 411
  vocab_sup_file: ./data/vocab/vocab_sup_PE_I.csv

Model:
  pretrained_model_path: ./ckpt/pretrain.pt
  drop_rate: 0.1
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1

Dataset:
  train_file: ./data/train_PE_I.csv
  test_file: ./data/test_PE_I.csv
  batch_size: 32
  num_workers: 8

Optimizer:
  lr_rate: 0.00005
  lr_rate_reg: 0.0001
  weight_decay: 0.01
  warmup_ratio: 0.05

Trainer:
  max_epochs: 20
  seed: 1
  tolerance: 5
  device: gpu
  output_dir: ./output/transpolymer_pe_i
