# @package _global_
defaults:
  - /Run: default
  - /Logger: default
  - /Dataset: ???
  - /Graph_converter: ???
  - /Model: ???
  - /Trainer: default
  - /Optimizer: Adam
  - /Learning_rate: Cosine
  - /Loss: L1Loss_IgnoreNanMetricWrapper
  - _self_

Global:
  label_names: ['energy_per_atom', 'force', 'stress', 'magmom']
  model_name: ???
  dataset_name: ???
  do_train: True
  do_eval: False
  do_test: False
  seed: 42

Experiment:
  name_for_best_metric: "energy_per_atom"
  prim_eager_enabled: True
  prim_backward_white_list: ['concat_grad', 'gather_grad', 'layer_norm_grad', 'split_grad']

_Metric:
  keys: ${Global.label_names}
  values:
    - ${Loss}
    - ${Loss}
    - ${Loss}
    - ${Loss}

Predict:
  graph_converter: ${Graph_converter}
  eval_with_no_grad: False

hydra:
  job:
    name: mlip
    chdir: True
  run:
    dir: ./output/${Global.model_name}_${Global.dataset_name}_${hydra.job.name}/t_${now:%Y%m%d_%H%M%S}_seed_${Global.seed}

# ==========================================
# Custom parameters (will override defaults)
# ==========================================

# Trainer:
#   max_epochs: 20
#   save_freq: 1
#   log_freq: 1
#   eval_with_no_grad: False

# Learning_rate:
#   __init_params__:
#     eta_min: 1e-5
#     by_epoch: False
