Global:
  label_names: ["homo"]
  do_train: True
  do_eval: False
  do_test: False

Dataset:
  dataset:
    __class_name__: QM9Dataset
    __init_params__:
      path: "./data/qm9"
      property_names: ${Global.label_names}
    num_workers: 4
    use_shared_memory: False
  split_dataset_ratio:
    train: 0.8
    val: 0.1
    test: 0.1
  train_sampler:
    __class_name__: BatchSampler
    __init_params__:
      shuffle: True
      drop_last: False
      batch_size: 64
  val_sampler:
    __class_name__: BatchSampler
    __init_params__:
      shuffle: False
      drop_last: False
      batch_size: 64
  test_sampler:
    __class_name__: BatchSampler
    __init_params__:
      shuffle: False
      drop_last: False
      batch_size: 64

Model:
  __class_name__: WDMPNN
  __init_params__:
    hidden_size: 300
    depth: 3
    dropout: 0.0
    ffn_hidden_size: 300
    ffn_num_layers: 2
    aggregation: mean
    aggregation_norm: 100.0
    atom_fdim: 133
    bond_fdim: 14
    bias: True
    output_size: 1
    loss_type: mse_loss
    property_names: ${Global.label_names}

Trainer:
  max_epochs: 100
  seed: 42
  output_dir: ./output/wd_mpnn_qm9_homo
  save_freq: 20
  log_freq: 10
  start_eval_epoch: 1
  eval_freq: 1
  pretrained_model_path: null
  pretrained_weight_name: null
  resume_from_checkpoint: null
  use_amp: False
  amp_level: 'O1'
  eval_with_no_grad: True
  gradient_accumulation_steps: 1
  best_metric_indicator: 'eval_metric'
  name_for_best_metric: "homo"
  greater_is_better: False
  compute_metric_during_train: True
  metric_strategy_during_eval: 'epoch'
  use_visualdl: False
  use_wandb: False
  use_tensorboard: False

Optimizer:
  __class_name__: Adam
  __init_params__:
    lr:
      __class_name__: OneCycleLR
      __init_params__:
        max_learning_rate: 0.001
        by_epoch: True

Metric:
  homo:
    __class_name__: paddle.nn.L1Loss
    __init_params__: {}
