# =========================================================
# Base dataset parameters (shared by train/val/test)
# =========================================================
dataset_base_params: &dataset_base_params
  energy_key: ${Experiment.energy_key}
  force_key: ${Experiment.force_key}
  stress_key: ${Experiment.stress_key}
  build_structure_cfg:
    format: ase_atoms
    primitive: False
    niggli: False
    num_cpus: 10
  build_graph_cfg: ${Graph_converter}
  filter_unvalid: False

# =========================================================
# Sampler configuration (reusable aliases)
# =========================================================
train_sampler: &train_sampler
  __class_name__: BatchSampler
  __init_params__:
    shuffle: True
    drop_last: True
    batch_size: 2 # 16 for 4 GPUs, total batch size = 16 * 4 = 64

val_sampler: &val_sampler
  __class_name__: BatchSampler
  __init_params__:
    shuffle: False
    drop_last: False
    batch_size: 16

test_sampler: &test_sampler
  __class_name__: BatchSampler
  __init_params__:
    shuffle: False
    drop_last: False
    batch_size: 16

# =========================================================
# Train / Validation / Test dataset configuration
# =========================================================
train:
  dataset:
    __class_name__: HighLevelWaterDataset
    __init_params__:
      <<: *dataset_base_params
      path: "${Run.data_dir}/high_level_water/high_level_water.xyz"
    num_workers: 0
    use_shared_memory: False
  sampler: *train_sampler

val:
  dataset:
    __class_name__: HighLevelWaterDataset
    __init_params__:
      <<: *dataset_base_params
      path: "${Run.data_dir}/high_level_water/high_level_water.xyz"
    num_workers: 0
    use_shared_memory: False
  sampler: *val_sampler

test:
  dataset:
    __class_name__: HighLevelWaterDataset
    __init_params__:
      <<: *dataset_base_params
      path: "${Run.data_dir}/high_level_water/high_level_water.xyz"
    num_workers: 0
    use_shared_memory: False
  sampler: *test_sampler
