# @package _global_
defaults:
  - /Run: default
  - /Logger: default
  - /Dataset: high_level_water
  - /Graph_converter: M3GNetGraphConvertor
  - /Model: m3gnet
  - /Trainer: default
  - /Optimizer: Adam
  - /Learning_rate: Step
  - /Loss: L1Loss_IgnoreNanMetricWrapper
  - _self_

Global:
  label_names: ['energy', 'force']
  model_name: "chgnet"
  dataset_name: "mptrj"
  do_train: True
  do_eval: False
  do_test: False
  seed: 42

Experiment:
  name_for_best_metric: "energy"
  prim_eager_enabled: True
  prim_backward_white_list: ['stack_grad', 'assign_grad']
  energy_key: 'energy'
  force_key: 'force'
  stress_key: null  # 'stress' - high level water data does not support stress

_Metric:
  keys: ${Global.label_names}
  values:
    - ${Loss}
    - ${Loss}

Predict:
  graph_converter: ${Graph_converter}
  eval_with_no_grad: False

hydra:
  job:
    name: mlip
    chdir: True
  run:
    dir: ./output/${Global.model_name}_${Global.dataset_name}_${hydra.job.name}/t_${now:%Y%m%d_%H%M%S}_seed_${Global.seed}

# ==========================================
# Custom parameters (will override defaults)
# ==========================================

Trainer:
  max_epochs: 20
  save_freq: 1
  log_freq: 1
  # Pretrained model path, if null, no pretrained model will be loaded
  pretrained_model_path: "https://paddle-org.bj.bcebos.com/paddlematerial/checkpoints/interatomic_potentials/mattersim/mattersim_1M.zip"
  # Pretrained weight name, will be used when pretrained_model_path is a directory
  pretrained_weight_name: mattersim-v1.0.0-1M_model.pdparams #'latest.pdparams'
  eval_with_no_grad: False
