# @package _global_
defaults:
  - Run: default
  - Logger: default
  - Dataset: mp2018
  - Dataset/transform: no_scaling
  - Graph_converter: ComformerGraphConverter
  - Model: comformer
  - Trainer: default
  - Optimizer: AdamW
  - Learning_rate: OneCycleLR
  - Loss: L1Loss
  - _self_

Global:
  label_names: ["K"]
  model_name: "comformer"
  dataset_name: "mp2018"
  do_train: True
  do_eval: False
  do_test: False
  seed: 42

Experiment:
  name_for_best_metric: ${Global.label_names[0]}

_Metric:
  keys: ${Global.label_names}
  values:
    - ${Loss}

Predict:
  graph_converter: ${Graph_converter}
  eval_with_no_grad: True
  post_transforms:
    - __class_name__: PowerData
      __init_params__:
        exp: 10
        apply_keys: ${Global.label_names[0]}

hydra:
  job:
    name: ${Global.label_names[0]}
    chdir: True
  run:
    dir: ./output/${Global.model_name}_${Global.dataset_name}_${hydra.job.name}/t_${now:%Y%m%d_%H%M%S}_seed_${Global.seed}

# ==========================================
# Custom parameters (will override defaults)
# ==========================================

Trainer:
  max_epochs: 500
  # save_freq: 1
  # log_freq: 1

Graph_converter:
  __init_params__:
    max_neighbors: 16

Learning_rate:
  __init_params__:
    max_learning_rate: 0.0001

Model:
  __init_params__:
    conv_layers: 3


log10_transform: &log10_transform
  - __class_name__: Log10
    __init_params__:
      apply_keys: ${Global.label_names[0]}

Dataset:
  train:
    dataset:
      __init_params__:
        transforms: *log10_transform
  val:
    dataset:
      __init_params__:
        transforms: *log10_transform
  test:
    dataset:
      __init_params__:
        transforms: *log10_transform
