Global:
  do_train: True
  do_eval: True
  do_test: False

Trainer:
  max_epochs: 2000
  seed: 42
  output_dir: ./output/omatg_mp20_dng_linear_sde
  save_freq: 100
  log_freq: 10
  start_eval_epoch: 1
  eval_freq: 1
  pretrained_model_path: null
  resume_from_checkpoint: null
  use_amp: False
  amp_level: 'O1'
  eval_with_no_grad: True
  gradient_accumulation_steps: 1
  best_metric_indicator: 'eval_loss'
  name_for_best_metric: "loss"
  greater_is_better: False
  compute_metric_during_train: False
  metric_strategy_during_eval: 'step'
  use_visualdl: False
  use_wandb: False
  use_tensorboard: False

Model:
  __class_name__: OMATGCSPNetFull
  __init_params__:
    hidden_dim: 512
    num_layers: 6
    max_atoms: 100
    act_fn: silu
    dis_emb: sin
    num_freqs: 128
    edge_style: fc
    cutoff: 7.0
    max_neighbors: 20
    ln: True
    ip: True
    smooth: False
    pred_type: True
    pred_scalar: False
    time_embed_dim: 256

Optimizer:
  __class_name__: Adam
  __init_params__:
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.01
    lr:
      __class_name__: Cosine
      __init_params__:
        learning_rate: 0.001
        by_epoch: True

Dataset:
  train:
    dataset:
      __class_name__: OMATGStructureDataset
      __init_params__:
        file_path: "./data/mp_20/train.lmdb"
        property_keys: []
        lazy_storage: True
        convert_to_fractional: True
        niggli_reduce: False
    loader:
      num_workers: 0
      use_shared_memory: False
      collate_fn: DefaultCollator
    sampler:
      __class_name__: BatchSampler
      __init_params__:
        shuffle: True
        drop_last: False
        batch_size: 512
  val:
    dataset:
      __class_name__: OMATGStructureDataset
      __init_params__:
        file_path: "./data/mp_20/val.lmdb"
        property_keys: []
        lazy_storage: True
        convert_to_fractional: True
        niggli_reduce: False
    loader:
      num_workers: 0
      use_shared_memory: False
      collate_fn: DefaultCollator
    sampler:
      __class_name__: BatchSampler
      __init_params__:
        shuffle: False
        drop_last: False
        batch_size: 512
  test:
    dataset:
      __class_name__: OMATGStructureDataset
      __init_params__:
        file_path: "./data/mp_20/test.lmdb"
        property_keys: []
        lazy_storage: True
        convert_to_fractional: True
        niggli_reduce: False
    loader:
      num_workers: 0
      use_shared_memory: False
      collate_fn: DefaultCollator
    sampler:
      __class_name__: DistributedBatchSampler
      __init_params__:
        shuffle: False
        drop_last: False
        batch_size: 512

Sample:
  data:
    dataset:
      __class_name__: OMATGStructureDataset
      __init_params__:
        file_path: "./data/mp_20/test.lmdb"
        property_keys: []
        lazy_storage: True
        convert_to_fractional: True
        niggli_reduce: False
    sampler:
      __class_name__: BatchSampler
      __init_params__:
        shuffle: False
        drop_last: False
        batch_size: 128
  build_structure_cfg:
    format: array
    niggli: False
  model_sample_params:
    num_inference_steps: 100
