# @package _global_
defaults:
  - /Run: default
  - /Logger: default
  - /Dataset: mp2018
  - /Dataset/transform: custom_scaling
  - /Graph_converter: CrystalNN
  - /Model: dimenet++
  - /Trainer: default
  - /Optimizer: Adam
  - /Learning_rate: Cosine
  - /Loss: L1Loss
  - _self_

Global:
  label_names: ["formation_energy_per_atom"]
  model_name: "dimenet++"
  dataset_name: "mp2018"
  do_train: True
  do_eval: False
  do_test: False
  seed: 42

Experiment:
  name_for_best_metric: ${Global.label_names[0]}

_Metric:
  keys: ${Global.label_names}
  values:
    - ${Loss}

Predict:
  graph_converter: ${Graph_converter}
  eval_with_no_grad: True

hydra:
  job:
    name: ${Global.label_names[0]}
    chdir: True
  run:
    dir: ./output/${Global.model_name}_${Global.dataset_name}_${hydra.job.name}/t_${now:%Y%m%d_%H%M%S}_seed_${Global.seed}

# ==========================================
# Custom parameters (will override defaults)
# ==========================================

# Trainer:
#   max_epochs: 2
#   save_freq: 1
#   log_freq: 1

Dataset:
  train:
    sampler: {__init_params__: {drop_last: True, batch_size: 32}}
  val:
    sampler: {__init_params__: {batch_size: 128}}
  test:
    sampler: {__init_params__: {batch_size: 128}}
  transform: {__init_params__: {mean: -1.6519675510987046, std: 1.0694354273392233}}

Model:
  __init_params__: {loss_type: 'l1_loss'}
