
dataset:
  structures_path: "./data/structures.pickle"
  mp_ids_path: "./data/mp_ids.pickle"
  ehull_path: "./data/formation_energy.pickle"

  cutoff: 4.0
  split_list: [0.9, 0.05, 0.05]

model:
  dim_node_embedding: 16
  dim_edge_embedding: 100
  dim_state_embedding: 2
  nblocks: 3
  hidden_layer_sizes_input: [64, 32]
  hidden_layer_sizes_conv: [64, 64, 32]
  nlayers_set2set: 1
  niters_set2set: 2
  hidden_layer_sizes_output: [32, 16]
  is_classification: False
  activation_type: "softplus2"
  cutoff: 4.0
  gauss_width: 0.5


lr_cfg:
  T_max: 1000
  eta_min: 0.00001
  learning_rate: 0.001
epochs: 2000
batch_size: 128

save_path: "./checkpoints/megnet_3d_debug"
