dataset:
  name: "2D_ehull"
  data_paths:
    structures: "./data/2D_structure/structures_0621.pickle"
    ehulls: "./data/2D_structure/ehulls_0621.pickle"
    name_formulas: "./data/2D_structure/formulas_0621.pickle"
  preprocess:
    # clip the data to a range
    # clip:
    #   # the key must be the same as in dataset/data_path
    #   ehulls: [-1, 2]
    # select the data in a range
    select:
      # the key must be the same as in dataset/data_path
      ehulls: [-0.5, 1]
    # normalize the data
    normalize:
      # the mean and std of the data
      ehulls: [-0.27, 0.344]

  cutoff: 4.0
  split_list: [0.9, 0.05, 0.05]

# select the best model by main_key
main_key: "ehulls"

model:
  dim_node_embedding: 24
  dim_edge_embedding: 100
  dim_state_embedding: 2
  nblocks: 6
  hidden_layer_sizes_input: [96, 48]
  hidden_layer_sizes_conv: [96, 96, 48]
  nlayers_set2set: 1
  niters_set2set: 2
  hidden_layer_sizes_output: [48, 24]
  is_classification: False
  activation_type: "softplus2"
  cutoff: 4.0
  gauss_width: 0.5
  prediction_keys: ["ehulls"]
  dropout: 0.5
  pretrained: './checkpoints/megnet_3d_pretrain_mp_select_10_norm_lr_0.001_run_large/best.pdparams'


lr_cfg:
  T_max: 1000
  eta_min: 0.00001
  learning_rate: 0.0005
epochs: 2000
batch_size: 128

save_path: "./checkpoints/megnet_2d_pretraind_by_mp"
